language: python
python:
  - "2.7"
install:
  - pip install -e .
  - pip install coverage coveralls --use-mirrors
script: cd tests && coverage run --source=../pydic/ -m unittest discover
after_success:
  - coveralls
