language: python
python:
  - "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libdb5.1 libdb5.1-dev
 - sudo ln -s /usr/lib/x86_64-linux-gnu/libdb-5.1.a /usr/lib/libdb-5.1.a
install:
  - pip install -e .
  - pip install coverage coveralls --use-mirrors
script: cd tests && coverage run -m unittest discover
after_success:
  - coveralls
